language: generic
branches:
  only:
  - master
cache:
  directories:
  - vendor
services:
- docker
sudo: required
install:
- make bootstrap
script:
- make build test dist prep-bintray-json
deploy:
  provider: bintray
  skip_cleanup: true
  file: _scripts/ci/bintray-ci.json
  user: deis-admin
  key:
    secure: Yt4PKTVsl1mRky+PKP/CQNKcHG333Iu3gvKFoLiDR8CM+Eu/XPoi+YV1ARUMN0vFmht5u8Iy2d1BJ4mFRaNwNyTNGf2Wo4M1583YMA3ujn5+92Wv3kpQeczE0CmUCNfKELnOe+/MKQ+RuLDtnX6kZCXubr0uLqWeWDtb+HHvGVAWjI/3koefgxF7nfIjDA8e8q7RTJRliNF2Ion3V8c6gX7M17zBa1mgqgrvq8BQ3k46L4SmPkAbeDXMYkFYf0UyHgFPFpVsSOdARBL99BS1W8yvTeIBwOa/JMVK29nyAwpHmN/I4R5YId0IIGZE5G+eyPyaRc5Kk7DGoIo6+dj4z0MeBVUxWOFuXdqfPR0rEi4LphyrjVgoduUK7nS4D1QsREWP13t1XoCPNRjReUWGQ1W2Slm4z0+J8OyHC2A+lONIigJRxmVAfTuDGd+X08teodbuHNNO2QLn2jiZ5eS4ttgwiaKDnCRhmCsHKMXlTe4ZBOki4GT/emjLtDzYiqu+qOddUkG72cn+3qVpUvZRoVj0Wqk11BH+0bcQFiy/kZZHk1lR8dKuzUCopX+bCuq1lC+zbD40klnPjcBK2YcKv6mrSBIz7w5Ok1+QEIxVHg/WWLTJ9zL3pFDzjeq4Up/Dd/GkYuv/xqZA1Rd/zPHOXbi8hps2Z9Pu7SU84DyPQ7A=
  on:
    branch: master
